name: Linux Unit tests
on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install cifs-utils procps conntrack -y
        GO111MODULE=off go get github.com/rexray/gocsi/csc

    - name: Build Test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make verify
        go test -covermode=count -coverprofile=profile.cov ./pkg/...
        export DOCKER_CLI_EXPERIMENTAL=enabled && make container

    - name: Integration Testing
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make
        make integration-test

    - name: Sanity test
      env: 
        isRunningGithubActions1: ${GITHUB_ACTIONS}
        isRunningGithubActions2: ${{ github.actions }}
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make
        echo "CHECK GITHUB ACTIONS\n"
        echo ${{ env.isRunningGithubActions1 }}
        echo ${{ env.isRunningGithubActions2 }}
        make sanity-test

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
